# Server
server.port=8088

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://3.136.16.248:5432/banking-proccesses?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=postgres13
spring.datasource.driverClassName=org.postgresql.Driver

# JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.banco.rpa=DEBUG
logging.file.name=logs/banking-rpa.log

# Banking URLs
banking.bbva.url=https://www.bbvanetcash.pe
banking.bcp.url=https://www.tlcbcp.com/
banking.ibk.url=https://empresas.interbank.pe/
banking.alfinapi.url=https://apibaasdev.alfinbanco.pe
banking.alfintoken.url=https://login.microsoftonline.com/e6b6af19-005a-4c9c-91a3-37fed2cbaed8/oauth2/v2.0/token

# Api key para captcha
2captcha.api.key=c6f853bc3d42536da7c8a34ceeac3942
2captcha.timeout=120
2captcha.polling.interval=5
2captcha.polling.maxIntentos=3

# variable de produccion
app.production=true

# Datos de enmarascamiento de proxy
brightdata.host=brd.superproxy.io
brightdata.port=33335
brightdata.username=brd-customer-hl_e813ba1f-zone-residential_proxy1
brightdata.password=hs1h8udhe67a